---
- name: install nagios reqs (Ubuntu)
  apt:
   name:
    - autoconf
    - gcc
    - libc6
    - make
    - wget
    - unzip
    - libssl-dev
    - apache2
    - php
    - libapache2-mod-php7.2
    - libgd-dev
    - build-essential
   state: latest
   force: true
   update_cache: true
  become: true
  when: ansible_distribution == "Ubuntu"

- name: install nagios (Ubuntu)
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.14.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

